### PR TITLE
Metadata updates

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/DSK8uoaE/63-metadata-updates-part-3

- removes all double quotes
- remove  unpublished `screenC`  from the study file

All changes have been applied to `prod61`

```
[sbesson@prod61-omeroreadwrite ~]$ PYTHONPATH=/opt/omero/server/OMERO.server/lib/python/ python /idr/metadata/pyidr/study_parser.py idr0008-study.txt --check
INFO:pyidr.study_parser:Parsing idr0008-study.txt
WARNING:pyidr.study_parser:Unknown key: Study Type Term Accession Number
WARNING:pyidr.study_parser:Unknown key: Study Organism Term Accession Number
INFO:omero.util.Resources:Starting
Using session for public@localhost:4064. Idle timeout: 10 min. Current group: Public
INFO:pyidr.study_parser:Checking Screen idr0008-rohn-actinome/screenA
INFO:pyidr.study_parser:No annotations mismatch detected
INFO:pyidr.study_parser:Checking Screen idr0008-rohn-actinome/screenB
INFO:pyidr.study_parser:No annotations mismatch detected
INFO:omero.gateway:closed connection (uuid=None)
INFO:omero.util.Resources:Halted
```

### CODE REVIEW

**Comment by joshmoore** [comment]
Validation in travis happens in the parent repo, right?

**Comment by sbesson** [comment]
Yes there are actually two levels of validation: 
- the basic language validation i.e. `flake8` and `yamllint` 
- the study parser validation which currently only happens at the parent repo

I didn't activate Travis for this repository it seems but can do so now if that is valuable. For the latter to happen per study repository, we might need to come back to the decoupling of [pyidr/](https://github.com/IDR/idr-metadata/tree/IDR-0.6.0/pyidr) to e.g. https://github.com/IDR/idr-py or a separate utility project (at least before we move to more official schema validation tools)

**Comment by joshmoore** [comment]
Can't hurt to activate, eh?

**Comment by sbesson** [comment]
Done in 141b71e and  9014388

**Pull request merged**
